apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-deployment
  namespace: camping
  labels:
    app: member-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: member-app
  template:
    metadata:
      labels:
        app: member-app
    spec:
      containers:
        - name: camping-member
          image: campingacr.azurecr.io/member
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: acr-registry