
server:
  port: 8080

spring:
  application:
    name: amf-portal-board
  profile:
    active: default
  profiles:
    include: oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://basecamp.mysql.database.azure.com:3306/member?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: camper
    password: qwer1234!!
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug
